service: benchmark-serverless


custom:
  region: ${opt:region, env:AWS_REGION, "us-east-1"}
  stage: ${opt:stage, env:STAGE, "localdev"}

plugins:
  modules: ${file(./serverless.js):modules}

provider:
  name: aws
  runtime: nodejs16.x
  region: ${self:custom.region}
  stage: ${self:custom.stage}
  environment:
    STAGE: ${self:custom.stage}
  timeout: 30 # seconds (`300` max)
  memorySize: 128 # MB value (`1024` default)

functions:
  base:
    handler: index.handler
    events: # Use a generic proxy to allow Express app to route.
      - http: ANY /base
      - http: 'ANY /base/{proxy+}'

  individual:
    handler: index.handler
    package:
      individually: true
    events: # Use a generic proxy to allow Express app to route.
      - http: ANY /individual
      - http: 'ANY /individual/{proxy+}'

# TODO(JETPACK): Add layers
